version: 2.1

references:
  images:
    go: &GOLANG_IMAGE cimg/go:1.14
#    python: &PYTHON_IMAGE circleci/python:2.7-stretch
    ci_machine: &CI_MACHINE_IMAGE ubuntu-1604:201903-01

  paths:
    test-results: &TEST_RESULTS_DIR bin

  environment: &ENVIRONMENT
    TEST_RESULTS_DIR: *TEST_RESULTS_DIR
    GIT_EMAIL : "zup-ci@zup.com.br"
    GIT_USERNAME: "zup-ci"
    GIT_NAME: "Zup CI"
    BUILD_IMAGE: *GOLANG_IMAGE

  filters: &FILTERS
    branches:
      only:
        - master
        - /^release-.*/
        - qa

#  filters-release: &FILTERS_RELEASE
#    branches:
#      only:
#        - /^release-.*/

executors:
  ritchie-server-executor:
    machine:
      image: *CI_MACHINE_IMAGE
    working_directory: ~/workspace

  ritchie-executor:
    docker:
      - image: *GOLANG_IMAGE
        user: root
    working_directory: ~/workspace


#  delivery-executor:
#    docker:
#      - image: *PYTHON_IMAGE
#        user: root
#    working_directory: /workspace

jobs:
  lint:
    executor: ritchie-server-executor
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            download=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
            wget -O- -q $download | sh -s -- -b /go/bin/ v1.24.0
            circleci-install golang 1.13
      - run: go mod download
      - run:
          name: lint
          command: |
            /go/bin/golangci-lint run
  test:
    executor: ritchie-server-executor
    environment:
      <<: *ENVIRONMENT
    steps:

      - checkout

      - run:
          name: Running test
          command: |
            mkdir -p $TEST_RESULTS_DIR
            docker-compose -f docker-compose-ci.yml run server

      - store_test_results:
          path: *TEST_RESULTS_DIR
      - store_artifacts:
          path: *TEST_RESULTS_DIR
      - run:
          name: codecov upload
          when: always
          command: bash <(curl -s https://codecov.io/bash)

  build:
    executor: ritchie-executor
    branches:
    steps:
      - checkout
      - run:
          name: Running build
          command: |
            . ./version.sh
            make build-circle
      - persist_to_workspace:
          root: .
          paths:
            - bin
      - store_test_results:
          path: *TEST_RESULTS_DIR
      - store_artifacts:
          path: *TEST_RESULTS_DIR

  docker:
    executor: ritchie-server-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - run:
          name: Creating docker image
          command: |
            make build-container-circle

  delivery:
    executor: delivery-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Delivering cli binary
          command: |
            pip install awscli
            . ./version.sh
            . ./bucket.sh
            . ./credentials.sh
            make delivery

  release:
    environment:
      <<: *ENVIRONMENT
    executor: delivery-executor
    steps:
      - checkout
      - run:
          name: Releasing
          command: |
            . ./version.sh
            make release


workflows:
  build_and_test:
    jobs:
#      - lint:
#          filters:
#            <<: *FILTERS
#      - test:
#          filters:
#            <<: *FILTERS
      - build:
          filters:
            <<: *FILTERS
#          requires:
#            - test
#            - lint
      - docker:
          filters:
            <<: *FILTERS
          requires:
            - build
#      - delivery:
#          filters:
#            <<: *FILTERS
#          requires:
#            - build
#      - release:
#          filters:
#            <<: *FILTERS_RELEASE
#          requires:
#            - build
